export const CREATE_DONATION_REQUEST = 'projects/CREATE_DONATION_REQUEST';
export const CREATE_DONATION_SUCCESS = 'projects/CREATE_DONATION_SUCCESS';
export const CREATE_DONATION_FAILURE = 'projects/CREATE_DONATION_FAILURE';

export const FETCH_PROJECTS_REQUEST = 'projects/FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_SUCCESS = 'projects/FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'projects/FETCH_PROJECTS_FAILURE';
