export const CREATE_PROJECT_REQUEST = 'projects/CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_SUCCESS = 'projects/CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'projects/CREATE_PROJECT_FAILURE';

export const FETCH_PROJECTS_REQUEST = 'projects/FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_SUCCESS = 'projects/FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'projects/FETCH_PROJECTS_FAILURE';

export const DELETE_PROJECT_REQUEST = 'projects/DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'projects/DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'projects/DELETE_PROJECT_FAILURE';

export const UPDATE_PROJECT_REQUEST = 'projects/UPDATE_PROJECT_REQUEST';
export const UPDATE_PROJECT_SUCCESS = 'projects/UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAILURE = 'projects/UPDATE_PROJECT_FAILURE';

export const FETCH_PROJECT_REQUEST = 'projects/FETCH_PROJECT_REQUEST';
export const FETCH_PROJECT_SUCCESS = 'projects/FETCH_PROJECT_SUCCESS';
export const FETCH_PROJECT_FAILURE = 'projects/FETCH_PROJECT_FAILURE';
