export const CREATE_PROJECT_REQUEST = 'projects/CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_SUCCESS = 'projects/CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'projects/CREATE_PROJECT_FAILURE';

export const FETCH_PROJECTS_REQUEST = 'projects/FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_SUCCESS = 'projects/FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'projects/FETCH_PROJECTS_FAILURE';
