export const CREATE_PROJECT_REQUEST = 'projects/CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_SUCCESS = 'projects/CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'projects/CREATE_PROJECT_FAILURE';
